// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo88-udVK0c116sKi__kg0WXfdwLj7des',
    appId: '1:154863278677:web:cf8b84abc79a76ce4592dc',
    messagingSenderId: '154863278677',
    projectId: 'apptact-a4f0c',
    authDomain: 'apptact-a4f0c.firebaseapp.com',
    storageBucket: 'apptact-a4f0c.firebasestorage.app',
    measurementId: 'G-KMXT2Z52GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAnL1daAOEdSNHkBUhrSVXKuJoTqzp5AY',
    appId: '1:154863278677:android:0e483083ffeadf074592dc',
    messagingSenderId: '154863278677',
    projectId: 'apptact-a4f0c',
    storageBucket: 'apptact-a4f0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtc9yxN29ECmDFyIikqDuKloH-ULD1Xj8',
    appId: '1:154863278677:ios:a6816fec09a27b454592dc',
    messagingSenderId: '154863278677',
    projectId: 'apptact-a4f0c',
    storageBucket: 'apptact-a4f0c.firebasestorage.app',
    iosClientId: '154863278677-c2bpeckamoc4o244mc0n1svusksmalt7.apps.googleusercontent.com',
    iosBundleId: 'com.jay.appTact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtc9yxN29ECmDFyIikqDuKloH-ULD1Xj8',
    appId: '1:154863278677:ios:34290ceff70482bc4592dc',
    messagingSenderId: '154863278677',
    projectId: 'apptact-a4f0c',
    storageBucket: 'apptact-a4f0c.firebasestorage.app',
    iosClientId: '154863278677-d8iphvp402555fi08bpactv7nb2i4aam.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStickerNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo88-udVK0c116sKi__kg0WXfdwLj7des',
    appId: '1:154863278677:web:ea4ffa87e0c22b3d4592dc',
    messagingSenderId: '154863278677',
    projectId: 'apptact-a4f0c',
    authDomain: 'apptact-a4f0c.firebaseapp.com',
    storageBucket: 'apptact-a4f0c.firebasestorage.app',
    measurementId: 'G-2M0QR92RJV',
  );
}
